inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'log/**/*'
    - 'spec/fixtures/**/*'
    - 'lib/granite/form/model/dirty.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false
